apiVersion: dp.wso2.com/v1alpha1
kind: APIPolicy
metadata:
  name: backend-jwt-token-policy
  namespace: apk
spec:
  override:
    backendJwtToken:
      isEnabled: true
    cORSPolicy:
      enabled: true
      accessControlAllowCredentials: false
      accessControlAllowOrigins:
        - "*"
      accessControlAllowHeaders:
        - authorization
      accessControlAllowMethods:
        - GET
        - POST
      accessControlExposeHeaders:
        - "*"
    oPAPolicy:
      serverURL: http://localhost:8181/v1/data
      policy: policyName
      rule: ruleName
      accessToken: accessToken
      sendAccessToken: false
      additionalProperties:
        - property1
        - property2
      maxOpenConnections: 5
      connectionTimeout: 30
  targetRef:
    group: gateway.networking.k8s.io
    kind: API
    name: http-bin-api
